version: '3.8'

services:
  app:
    build: .
    working_dir: /usr/app
    volumes:
      - .:/usr/app              
      - /usr/app/node_modules   
    ports:
      - "3000:3000"             
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev
