export const DONORS = [
  {
    id: 1,
    firstName: "Rajesh",
    lastName: "Sharma",
    gender: "Male",
    bloodGroup: "O+",
    age: 32,
    phone: "+91 9876543210",
    address: "Mumbai, Maharashtra",
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Verma",
    gender: "Female",
    bloodGroup: "A+",
    age: 28,
    phone: "+91 9823456789",
    address: "Delhi, Delhi",
  },
  {
    id: 3,
    firstName: "Amit",
    lastName: "Patel",
    gender: "Male",
    bloodGroup: "B+",
    age: 40,
    phone: "+91 9867543210",
    address: "Ahmedabad, Gujarat",
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Rao",
    gender: "Female",
    bloodGroup: "AB+",
    age: 35,
    phone: "+91 9812345678",
    address: "Bangalore, Karnataka",
  },
  {
    id: 5,
    firstName: "Vikas",
    lastName: "Singh",
    gender: "Male",
    bloodGroup: "O-",
    age: 45,
    phone: "+91 9845678901",
    address: "Kolkata, West Bengal",
  },
  {
    id: 6,
    firstName: "Anjali",
    lastName: "Nair",
    gender: "Female",
    bloodGroup: "B-",
    age: 29,
    phone: "+91 9898765432",
    address: "Chennai, Tamil Nadu",
  },
  {
    id: 7,
    firstName: "Sandeep",
    lastName: "Yadav",
    gender: "Male",
    bloodGroup: "A-",
    age: 38,
    phone: "+91 9834567890",
    address: "Lucknow, Uttar Pradesh",
  },
  {
    id: 8,
    firstName: "Meera",
    lastName: "Das",
    gender: "Female",
    bloodGroup: "AB-",
    age: 33,
    phone: "+91 9887654321",
    address: "Bhubaneswar, Odisha",
  },
  {
    id: 9,
    firstName: "Rohan",
    lastName: "Kapoor",
    gender: "Male",
    bloodGroup: "O+",
    age: 31,
    phone: "+91 9876123456",
    address: "Pune, Maharashtra",
  },
  {
    id: 10,
    firstName: "Kavita",
    lastName: "Gupta",
    gender: "Female",
    bloodGroup: "A+",
    age: 27,
    phone: "+91 9812340987",
    address: "Jaipur, Rajasthan",
  },
  {
    id: 11,
    firstName: "Arjun",
    lastName: "Mehta",
    gender: "Male",
    bloodGroup: "B+",
    age: 29,
    phone: "+91 9832198765",
    address: "Surat, Gujarat",
  },
  {
    id: 12,
    firstName: "Pooja",
    lastName: "Iyer",
    gender: "Female",
    bloodGroup: "AB+",
    age: 30,
    phone: "+91 9823450908",
    address: "Mysore, Karnataka",
  },
  {
    id: 13,
    firstName: "Sourav",
    lastName: "Mukherjee",
    gender: "Male",
    bloodGroup: "O-",
    age: 34,
    phone: "+91 9876504321",
    address: "Kolkata, West Bengal",
  },
  {
    id: 14,
    firstName: "Divya",
    lastName: "Bansal",
    gender: "Female",
    bloodGroup: "A-",
    age: 25,
    phone: "+91 9801234567",
    address: "Chandigarh, Punjab",
  },
  {
    id: 15,
    firstName: "Manoj",
    lastName: "Reddy",
    gender: "Male",
    bloodGroup: "B-",
    age: 42,
    phone: "+91 9890987654",
    address: "Hyderabad, Telangana",
  },
  {
    id: 16,
    firstName: "Sunita",
    lastName: "Joshi",
    gender: "Female",
    bloodGroup: "O+",
    age: 36,
    phone: "+91 9843123456",
    address: "Dehradun, Uttarakhand",
  },
  {
    id: 17,
    firstName: "Varun",
    lastName: "Chauhan",
    gender: "Male",
    bloodGroup: "AB-",
    age: 37,
    phone: "+91 9856784321",
    address: "Shimla, Himachal Pradesh",
  },
  {
    id: 18,
    firstName: "Neha",
    lastName: "Agarwal",
    gender: "Female",
    bloodGroup: "B+",
    age: 31,
    phone: "+91 9876541234",
    address: "Indore, Madhya Pradesh",
  },
  {
    id: 19,
    firstName: "Ravi",
    lastName: "Pandey",
    gender: "Male",
    bloodGroup: "A+",
    age: 39,
    phone: "+91 9821765432",
    address: "Varanasi, Uttar Pradesh",
  },
  {
    id: 20,
    firstName: "Simran",
    lastName: "Malhotra",
    gender: "Female",
    bloodGroup: "O-",
    age: 28,
    phone: "+91 9812345671",
    address: "Amritsar, Punjab",
  },
  {
    id: 21,
    firstName: "Harsh",
    lastName: "Kumar",
    gender: "Male",
    bloodGroup: "B-",
    age: 33,
    phone: "+91 9833214567",
    address: "Patna, Bihar",
  },
  {
    id: 22,
    firstName: "Ayesha",
    lastName: "Khan",
    gender: "Female",
    bloodGroup: "AB+",
    age: 26,
    phone: "+91 9873412678",
    address: "Srinagar, Jammu & Kashmir",
  },
  {
    id: 23,
    firstName: "Gaurav",
    lastName: "Mishra",
    gender: "Male",
    bloodGroup: "O+",
    age: 30,
    phone: "+91 9845567890",
    address: "Bhopal, Madhya Pradesh",
  },
  {
    id: 24,
    firstName: "Bhavya",
    lastName: "Shukla",
    gender: "Female",
    bloodGroup: "A-",
    age: 35,
    phone: "+91 9814578901",
    address: "Raipur, Chhattisgarh",
  },
  {
    id: 25,
    firstName: "Yash",
    lastName: "Tiwari",
    gender: "Male",
    bloodGroup: "B+",
    age: 27,
    phone: "+91 9802345678",
    address: "Gwalior, Madhya Pradesh",
  },
];
