name: ✨ Feature Request
description: Suggest a feature request
title: "feat:"
labels: ["⭐ goal: addition", "🚦status: awaiting triage"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      placeholder: Add screenshots
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
          required: true

        - label: I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
          required: true

        

        - label: I want to work on this issue
